# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bloguser_privateblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateblog',
            name='tag',
            field=models.CharField(default='python', max_length=50),
        ),
    ]
