# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_privateblog_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(default='python', max_length=50),
        ),
    ]
