# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='privateblog',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
