# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('tags', models.CharField(default='python', max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
