# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost2',
            name='fuck',
            field=models.TextField(default='aaa'),
            preserve_default=False,
        ),
    ]
